name: QEC lib

on:
  workflow_call:

jobs:
  pr-build:
    name: Build and test
    if: startsWith(github.ref, 'refs/heads/pull-request/')
    strategy:
      fail-fast: false
      matrix:
        platform: ['amd64', 'arm64']
    runs-on: ${{ startsWith(github.repository, 'NVIDIA/cudaqx') && format('linux-{0}-cpu8', matrix.platform) || 'ubuntu-latest' }}
    container: ghcr.io/nvidia/cuda-quantum-devdeps:ext-cu12.0-gcc11-main
    permissions:
      actions: write
      contents: read
      pull-requests: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          set-safe-directory: true

      - name: Lookup PR info
        id: get-pr-info
        env:
          GH_TOKEN: ${{ github.token }}
        uses: nv-gha-runners/get-pr-info@main

      - name: Export PR info
        id: export-pr-info
        run: |
          echo "pr_number=${{ fromJSON(steps.get-pr-info.outputs.pr-info).number }}" >> $GITHUB_OUTPUT

      # ========================================================================
      # CUDA Quantum build
      # ========================================================================

      - name: Get required CUDAQ version
        id: get-cudaq-version
        uses: ./.github/actions/get-cudaq-version

      - name: Get CUDAQ build
        uses: ./.github/actions/get-cudaq-build
        with:
          repo: ${{ steps.get-cudaq-version.outputs.repo }}
          ref: ${{ steps.get-cudaq-version.outputs.ref }}
          token: ${{ secrets.CUDAQ_ACCESS_TOKEN }}
          pr-number: ${{ steps.export-pr-info.outputs.pr_number }}
          platform: ${{ matrix.platform }}

      # ========================================================================
      # Build library
      # ========================================================================

      - name: Build
        id: build
        uses: ./.github/actions/build-lib
        with:
          lib: "qec"
          pr-number: ${{ steps.export-pr-info.outputs.pr_number }}
          save-ccache: true
          platform: ${{ matrix.platform }}

      # ========================================================================
      # Run tests
      # ========================================================================
      
      - name: Run tests
        run: cmake --build ${{ steps.build.outputs.build-dir }} --target run_tests

      # ========================================================================
      # Run python tests
      # ========================================================================
 
      - name: Install python requirements
        run: |
          pip install numpy pytest cupy-cuda12x cuquantum-python-cu12
          if [ "${{ matrix.platform }}" = "amd64" ]; then
            # Install tensor network decoder dependencies on amd64
            pip install quimb torch opt_einsum stim
          fi

      - name: Run Python tests
        run: |
          if [ "${{ matrix.platform }}" = "amd64" ]; then
            # Run all tests on amd64
            cmake --build ${{ steps.build.outputs.build-dir }} --target run_python_tests
          else
            # Skip tensor network decoder tests on arm64
            PYTEST_ADDOPTS="--ignore=python/tests/test_tensor_network_decoder.py --ignore=python/cudaq_qec/plugins/decoders/test_tensor_network_decoder.py --ignore=python/cudaq_qec/plugins/decoders/tensor_network_utils/test_tensor_network_utils.py" \
            cmake --build ${{ steps.build.outputs.build-dir }} --target run_python_tests
          fi

      # ========================================================================
      # Run example tests
      # ========================================================================

      - name: Run example tests
        run: bash scripts/ci/test_examples.sh qec

